version: '3'

services:
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
     - "5557:5557"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/load_all_in_one_user_locustfile.py --master -H https://34.91.47.190
    working_dir: /mnt/locust/

  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/load_all_in_one_user_locustfile.py --worker --master-host master
    working_dir: /mnt/locust/
